//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_Mensajes
    {
        public int IdMensaje { get; set; }
        public int IdUsuarioRemitente { get; set; }
        public int IdUsuarioDestinatario { get; set; }
        public int IdEstado { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public bool Prioridad { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaLectura { get; set; }
        public Nullable<System.DateTime> FechaBorrado { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Sys_Usuarios Sys_Usuarios { get; set; }
        public virtual Com_MensajesEstado Com_MensajesEstado { get; set; }
    }
}
