//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_Clientes_Categorias
    {
        public int IdCliente { get; set; }
        public int IdCategoria { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Doc_Categorias Doc_Categorias { get; set; }
        public virtual Sys_Clientes Sys_Clientes { get; set; }
    }
}
