//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos_Tareas
    {
        public int IdDocumento { get; set; }
        public int IdTarea { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Doc_Documentos Doc_Documentos { get; set; }
        public virtual Doc_Documentos Doc_Documentos1 { get; set; }
        public virtual Tar_Tareas Tar_Tareas { get; set; }
        public virtual Tar_Tareas Tar_Tareas1 { get; set; }
    }
}
