//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PosiblesRespuestas
    {
        public int IdPosibleRespuesta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_Preguntas M_Preguntas { get; set; }
    }
}
