//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Preguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Preguntas()
        {
            this.M_PosiblesRespuestas = new HashSet<M_PosiblesRespuestas>();
            this.M_PreguntasResueltas = new HashSet<M_PreguntasResueltas>();
            this.Pry_Informes_Encuestas = new HashSet<Pry_Informes_Encuestas>();
        }
    
        public int IdPregunta { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public string Pregunta { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Orden { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_Encuestas M_Encuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PosiblesRespuestas> M_PosiblesRespuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PreguntasResueltas> M_PreguntasResueltas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_Informes_Encuestas> Pry_Informes_Encuestas { get; set; }
    }
}
