//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PreguntasResueltas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_PreguntasResueltas()
        {
            this.M_ValoresRespuesta = new HashSet<M_ValoresRespuesta>();
        }
    
        public int IdPreguntaResuelta { get; set; }
        public Nullable<int> IdEncuestaResuelta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public string TextoRespuesta { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_EncuestasResueltas M_EncuestasResueltas { get; set; }
        public virtual M_Preguntas M_Preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ValoresRespuesta> M_ValoresRespuesta { get; set; }
    }
}
