//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_TipCambio
    {
        public int idTipCambio { get; set; }
        public int idMoneda { get; set; }
        public System.DateTime FecTipCambio { get; set; }
        public Nullable<decimal> ValCompra { get; set; }
        public Nullable<decimal> ValVenta { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_Monedas M_Monedas { get; set; }
    }
}
