//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdlumenJorgeEntities : DbContext
    {
        public AdlumenJorgeEntities()
            : base("name=AdlumenJorgeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cms_MenuNodos> Cms_MenuNodos { get; set; }
        public virtual DbSet<Cms_Menus> Cms_Menus { get; set; }
        public virtual DbSet<Com_Mensajes> Com_Mensajes { get; set; }
        public virtual DbSet<Com_MensajesEstado> Com_MensajesEstado { get; set; }
        public virtual DbSet<Doc_ArchivosTipos> Doc_ArchivosTipos { get; set; }
        public virtual DbSet<Doc_Categorias> Doc_Categorias { get; set; }
        public virtual DbSet<Doc_Clientes_Categorias> Doc_Clientes_Categorias { get; set; }
        public virtual DbSet<Doc_Documentos> Doc_Documentos { get; set; }
        public virtual DbSet<Documentos_Tareas> Documentos_Tareas { get; set; }
        public virtual DbSet<M_Encuestas> M_Encuestas { get; set; }
        public virtual DbSet<M_EncuestasResueltas> M_EncuestasResueltas { get; set; }
        public virtual DbSet<M_Idiomas> M_Idiomas { get; set; }
        public virtual DbSet<M_Monedas> M_Monedas { get; set; }
        public virtual DbSet<M_Paises> M_Paises { get; set; }
        public virtual DbSet<M_Periodos> M_Periodos { get; set; }
        public virtual DbSet<M_PosiblesRespuestas> M_PosiblesRespuestas { get; set; }
        public virtual DbSet<M_Preguntas> M_Preguntas { get; set; }
        public virtual DbSet<M_PreguntasResueltas> M_PreguntasResueltas { get; set; }
        public virtual DbSet<M_Temas> M_Temas { get; set; }
        public virtual DbSet<m_TipCambio> m_TipCambio { get; set; }
        public virtual DbSet<M_ValoresRespuesta> M_ValoresRespuesta { get; set; }
        public virtual DbSet<Moduloes> Moduloes { get; set; }
        public virtual DbSet<Org_Areas> Org_Areas { get; set; }
        public virtual DbSet<Org_Cargos> Org_Cargos { get; set; }
        public virtual DbSet<Org_Donantes> Org_Donantes { get; set; }
        public virtual DbSet<Org_Empleados> Org_Empleados { get; set; }
        public virtual DbSet<Org_EmpleadosCargosHistorico> Org_EmpleadosCargosHistorico { get; set; }
        public virtual DbSet<Org_Empresas> Org_Empresas { get; set; }
        public virtual DbSet<Org_IdentificacionTipos> Org_IdentificacionTipos { get; set; }
        public virtual DbSet<Org_Proveedores> Org_Proveedores { get; set; }
        public virtual DbSet<Pry_Beneficiarios> Pry_Beneficiarios { get; set; }
        public virtual DbSet<Pry_Bitacoras> Pry_Bitacoras { get; set; }
        public virtual DbSet<Pry_CalendarioDonaciones> Pry_CalendarioDonaciones { get; set; }
        public virtual DbSet<Pry_CapacitacionBeneficiario> Pry_CapacitacionBeneficiario { get; set; }
        public virtual DbSet<Pry_Capacitaciones> Pry_Capacitaciones { get; set; }
        public virtual DbSet<Pry_DatosMuestras> Pry_DatosMuestras { get; set; }
        public virtual DbSet<Pry_DatosVariables> Pry_DatosVariables { get; set; }
        public virtual DbSet<Pry_DatosVerificadores> Pry_DatosVerificadores { get; set; }
        public virtual DbSet<PRY_EVALUACIONESACTIVIDADESPERIODO> PRY_EVALUACIONESACTIVIDADESPERIODO { get; set; }
        public virtual DbSet<Pry_EvaluacionHitos> Pry_EvaluacionHitos { get; set; }
        public virtual DbSet<PRY_EVALUACIONINDICADORESPERIODO> PRY_EVALUACIONINDICADORESPERIODO { get; set; }
        public virtual DbSet<PRY_EVALUACIONPROYECTOPERIODO> PRY_EVALUACIONPROYECTOPERIODO { get; set; }
        public virtual DbSet<Pry_Facilitadores> Pry_Facilitadores { get; set; }
        public virtual DbSet<Pry_Indicadores> Pry_Indicadores { get; set; }
        public virtual DbSet<Pry_Indicadores_Variables> Pry_Indicadores_Variables { get; set; }
        public virtual DbSet<Pry_IndicadoresProyecto_Programa> Pry_IndicadoresProyecto_Programa { get; set; }
        public virtual DbSet<Pry_IndicadoresTipos> Pry_IndicadoresTipos { get; set; }
        public virtual DbSet<Pry_IndicadoresVerificadores> Pry_IndicadoresVerificadores { get; set; }
        public virtual DbSet<Pry_Informes> Pry_Informes { get; set; }
        public virtual DbSet<Pry_Informes_Donantes> Pry_Informes_Donantes { get; set; }
        public virtual DbSet<Pry_Informes_Encuestas> Pry_Informes_Encuestas { get; set; }
        public virtual DbSet<Pry_Informes_Indicador> Pry_Informes_Indicador { get; set; }
        public virtual DbSet<Pry_Informes_Presupuestos> Pry_Informes_Presupuestos { get; set; }
        public virtual DbSet<Pry_Informes_Supuestos> Pry_Informes_Supuestos { get; set; }
        public virtual DbSet<Pry_InformesEstados> Pry_InformesEstados { get; set; }
        public virtual DbSet<PRY_INFORMESICA> PRY_INFORMESICA { get; set; }
        public virtual DbSet<PRY_INFORMESICADETALLE> PRY_INFORMESICADETALLE { get; set; }
        public virtual DbSet<PRY_INFORMESICADOCUMENTOS> PRY_INFORMESICADOCUMENTOS { get; set; }
        public virtual DbSet<PRY_INFORMESICAESTADOS> PRY_INFORMESICAESTADOS { get; set; }
        public virtual DbSet<PRY_INFORMESICAINDICADORES> PRY_INFORMESICAINDICADORES { get; set; }
        public virtual DbSet<PRY_INFORMESICAOBJETIVOS> PRY_INFORMESICAOBJETIVOS { get; set; }
        public virtual DbSet<PRY_INFORMESICATIPOS> PRY_INFORMESICATIPOS { get; set; }
        public virtual DbSet<Pry_MontoDonacion> Pry_MontoDonacion { get; set; }
        public virtual DbSet<Pry_Movimientos> Pry_Movimientos { get; set; }
        public virtual DbSet<Pry_NivelAceptacion> Pry_NivelAceptacion { get; set; }
        public virtual DbSet<Pry_Objetivos> Pry_Objetivos { get; set; }
        public virtual DbSet<Pry_ObjetivosClase> Pry_ObjetivosClase { get; set; }
        public virtual DbSet<PRY_PARTIDAGASTOS> PRY_PARTIDAGASTOS { get; set; }
        public virtual DbSet<PRY_PERIODOSPROYECTOS> PRY_PERIODOSPROYECTOS { get; set; }
        public virtual DbSet<Pry_Presupuesto> Pry_Presupuesto { get; set; }
        public virtual DbSet<Pry_PresupuestoTipo> Pry_PresupuestoTipo { get; set; }
        public virtual DbSet<Pry_ProductividadBeneficiario> Pry_ProductividadBeneficiario { get; set; }
        public virtual DbSet<Pry_Proyectos> Pry_Proyectos { get; set; }
        public virtual DbSet<Pry_Proyectos_Donantes> Pry_Proyectos_Donantes { get; set; }
        public virtual DbSet<Pry_Proyectos_NivelAceptacion> Pry_Proyectos_NivelAceptacion { get; set; }
        public virtual DbSet<Pry_ProyectosEstados> Pry_ProyectosEstados { get; set; }
        public virtual DbSet<Pry_ProyectosTipos> Pry_ProyectosTipos { get; set; }
        public virtual DbSet<Pry_Recursos> Pry_Recursos { get; set; }
        public virtual DbSet<Pry_Supuestos> Pry_Supuestos { get; set; }
        public virtual DbSet<Pry_Variables> Pry_Variables { get; set; }
        public virtual DbSet<Sys_Clientes> Sys_Clientes { get; set; }
        public virtual DbSet<Sys_Usuarios> Sys_Usuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tar_Bitacora> Tar_Bitacora { get; set; }
        public virtual DbSet<Tar_Listas> Tar_Listas { get; set; }
        public virtual DbSet<Tar_Permisos_Bitacora> Tar_Permisos_Bitacora { get; set; }
        public virtual DbSet<Tar_Tareas> Tar_Tareas { get; set; }
        public virtual DbSet<Tar_Visitas> Tar_Visitas { get; set; }
        public virtual DbSet<Tenants> Tenants { get; set; }
        public virtual DbSet<M_Plantillas> M_Plantillas { get; set; }
    }
}
