//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_EmpleadosCargosHistorico
    {
        public int IdEmpleadoCargo { get; set; }
        public int IdEmpleado { get; set; }
        public int IdCargo { get; set; }
        public System.DateTime FechaInicioCargo { get; set; }
        public Nullable<System.DateTime> FechaFinCargo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Org_Cargos Org_Cargos { get; set; }
        public virtual Org_Empleados Org_Empleados { get; set; }
    }
}
