//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Org_Empresas()
        {
            this.Org_Areas = new HashSet<Org_Areas>();
            this.Org_Proveedores = new HashSet<Org_Proveedores>();
            this.Pry_Objetivos = new HashSet<Pry_Objetivos>();
            this.Org_Donantes = new HashSet<Org_Donantes>();
            this.Sys_Usuarios = new HashSet<Sys_Usuarios>();
        }
    
        public int IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public string URL { get; set; }
        public string Telefono { get; set; }
        public string Logo { get; set; }
        public int IdIdentificacionTipo { get; set; }
        public string Identificacion { get; set; }
        public int IdPais { get; set; }
        public Nullable<int> IdMenuAdministracion { get; set; }
        public Nullable<int> IdMenuSuperior { get; set; }
        public Nullable<int> IdMenuIzquierdo { get; set; }
        public Nullable<int> IdMenuPanel { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> IdMenuSLDerecho { get; set; }
        public Nullable<int> IdMenuReportes { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdCategoriaDocumentos { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Cms_Menus Cms_Menus { get; set; }
        public virtual Cms_Menus Cms_Menus1 { get; set; }
        public virtual Cms_Menus Cms_Menus2 { get; set; }
        public virtual M_Paises M_Paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_Areas> Org_Areas { get; set; }
        public virtual Org_IdentificacionTipos Org_IdentificacionTipos { get; set; }
        public virtual Sys_Clientes Sys_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_Proveedores> Org_Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_Objetivos> Pry_Objetivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_Donantes> Org_Donantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Usuarios> Sys_Usuarios { get; set; }
    }
}
