//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Informes_Donantes
    {
        public int IdInforme { get; set; }
        public int IdDonante { get; set; }
        public Nullable<double> Donacion { get; set; }
        public Nullable<System.DateTime> FechaPrimeraDonacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaDonacion { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Org_Donantes Org_Donantes { get; set; }
        public virtual Pry_Informes Pry_Informes { get; set; }
    }
}
