//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_CapacitacionBeneficiario
    {
        public int IdCapacitacionBeneficiario { get; set; }
        public int IdCapacitacion { get; set; }
        public int IdBeneficiario { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public byte Status { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_Beneficiarios Pry_Beneficiarios { get; set; }
        public virtual Pry_Capacitaciones Pry_Capacitaciones { get; set; }
    }
}
