//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRY_EVALUACIONESACTIVIDADESPERIODO
    {
        public int IDOBJETIVO { get; set; }
        public long IDPERIODO { get; set; }
        public int IDPROYECTO { get; set; }
        public string OBSERVACIONES { get; set; }
        public int IdTenant { get; set; }
    
        public virtual PRY_EVALUACIONPROYECTOPERIODO PRY_EVALUACIONPROYECTOPERIODO { get; set; }
        public virtual Pry_Objetivos Pry_Objetivos { get; set; }
    }
}
