//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Supuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pry_Supuestos()
        {
            this.Pry_Informes_Supuestos = new HashSet<Pry_Informes_Supuestos>();
        }
    
        public int IdSupuesto { get; set; }
        public Nullable<int> IdObjetivo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Impacto { get; set; }
        public string PlanContingencia { get; set; }
        public int IdTenant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_Informes_Supuestos> Pry_Informes_Supuestos { get; set; }
        public virtual Pry_Objetivos Pry_Objetivos { get; set; }
    }
}
