//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Proyectos_NivelAceptacion
    {
        public int IdProyecto { get; set; }
        public int IdNivelAceptacion { get; set; }
        public double Valor { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_NivelAceptacion Pry_NivelAceptacion { get; set; }
        public virtual Pry_Proyectos Pry_Proyectos { get; set; }
    }
}
