//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRY_INFORMESICAINDICADORES
    {
        public int IDINFORME { get; set; }
        public int IDINDICADOR { get; set; }
        public string LOGROS { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_Indicadores Pry_Indicadores { get; set; }
        public virtual PRY_INFORMESICA PRY_INFORMESICA { get; set; }
    }
}
