//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRY_PERIODOSPROYECTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRY_PERIODOSPROYECTOS()
        {
            this.Pry_DatosMuestras = new HashSet<Pry_DatosMuestras>();
            this.Pry_EvaluacionHitos = new HashSet<Pry_EvaluacionHitos>();
            this.PRY_EVALUACIONINDICADORESPERIODO = new HashSet<PRY_EVALUACIONINDICADORESPERIODO>();
            this.PRY_EVALUACIONPROYECTOPERIODO = new HashSet<PRY_EVALUACIONPROYECTOPERIODO>();
            this.PRY_INFORMESICA = new HashSet<PRY_INFORMESICA>();
            this.PRY_INFORMESICA1 = new HashSet<PRY_INFORMESICA>();
            this.Pry_Movimientos = new HashSet<Pry_Movimientos>();
        }
    
        public long IdPeriodo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public bool Activo { get; set; }
        public int Secuencia { get; set; }
        public int IdTenant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_DatosMuestras> Pry_DatosMuestras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_EvaluacionHitos> Pry_EvaluacionHitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRY_EVALUACIONINDICADORESPERIODO> PRY_EVALUACIONINDICADORESPERIODO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRY_EVALUACIONPROYECTOPERIODO> PRY_EVALUACIONPROYECTOPERIODO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRY_INFORMESICA> PRY_INFORMESICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRY_INFORMESICA> PRY_INFORMESICA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_Movimientos> Pry_Movimientos { get; set; }
        public virtual Pry_Proyectos Pry_Proyectos { get; set; }
    }
}
