//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tar_Tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tar_Tareas()
        {
            this.Documentos_Tareas = new HashSet<Documentos_Tareas>();
            this.Documentos_Tareas1 = new HashSet<Documentos_Tareas>();
            this.Tar_Visitas = new HashSet<Tar_Visitas>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdLista { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Prioridad { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCompletado { get; set; }
        public Nullable<int> IdUsuarioCompletado { get; set; }
        public int IdTenant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos_Tareas> Documentos_Tareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos_Tareas> Documentos_Tareas1 { get; set; }
        public virtual Sys_Usuarios Sys_Usuarios { get; set; }
        public virtual Sys_Usuarios Sys_Usuarios1 { get; set; }
        public virtual Sys_Usuarios Sys_Usuarios2 { get; set; }
        public virtual Sys_Usuarios Sys_Usuarios3 { get; set; }
        public virtual Tar_Listas Tar_Listas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tar_Visitas> Tar_Visitas { get; set; }
    }
}
