//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_Documentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc_Documentos()
        {
            this.Tar_Tareas = new HashSet<Tar_Tareas>();
        }
    
        public int IdDocumento { get; set; }
        public int IdCategoria { get; set; }
        public int IdTipoArchivo { get; set; }
        public string Titulo { get; set; }
        public string PalabrasClaves { get; set; }
        public string Resumen { get; set; }
        public string Url { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Roles { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Doc_ArchivosTipos Doc_ArchivosTipos { get; set; }
        public virtual Doc_Categorias Doc_Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tar_Tareas> Tar_Tareas { get; set; }
    }
}
