//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PosiblesRespuestas
    {
        public int IdPosibleRespuesta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_Preguntas M_Preguntas { get; set; }
    }
}
