//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PreguntasResueltas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_PreguntasResueltas()
        {
            this.M_ValoresRespuesta = new HashSet<M_ValoresRespuesta>();
        }
    
        public int IdPreguntaResuelta { get; set; }
        public Nullable<int> IdEncuestaResuelta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public string TextoRespuesta { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_EncuestasResueltas M_EncuestasResueltas { get; set; }
        public virtual M_Preguntas M_Preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ValoresRespuesta> M_ValoresRespuesta { get; set; }
    }
}
