//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_TipCambio
    {
        public int idTipCambio { get; set; }
        public int idMoneda { get; set; }
        public System.DateTime FecTipCambio { get; set; }
        public Nullable<decimal> ValCompra { get; set; }
        public Nullable<decimal> ValVenta { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_Monedas M_Monedas { get; set; }
    }
}
