//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ValoresRespuesta
    {
        public int IdValorRespuesta { get; set; }
        public Nullable<int> IdPreguntaResuelta { get; set; }
        public string Valor { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_PreguntasResueltas M_PreguntasResueltas { get; set; }
    }
}
