//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Informes_Presupuestos
    {
        public int IdInforme { get; set; }
        public int IdPresupuesto { get; set; }
        public Nullable<double> Ejecutado { get; set; }
        public Nullable<double> Utilizacion { get; set; }
        public Nullable<int> Evaluacion { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_Informes Pry_Informes { get; set; }
        public virtual Pry_NivelAceptacion Pry_NivelAceptacion { get; set; }
        public virtual Pry_Presupuesto Pry_Presupuesto { get; set; }
    }
}
