//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Informes_Donantes
    {
        public int IdInforme { get; set; }
        public int IdDonante { get; set; }
        public Nullable<double> Donacion { get; set; }
        public Nullable<System.DateTime> FechaPrimeraDonacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaDonacion { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Org_Donantes Org_Donantes { get; set; }
        public virtual Pry_Informes Pry_Informes { get; set; }
    }
}
