//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_DatosVerificadores
    {
        public int IdDatosFuentes { get; set; }
        public Nullable<int> IdDatosMuestra { get; set; }
        public Nullable<int> IdVerificador { get; set; }
        public string Url { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_DatosMuestras Pry_DatosMuestras { get; set; }
        public virtual Pry_IndicadoresVerificadores Pry_IndicadoresVerificadores { get; set; }
    }
}
