//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Capacitaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pry_Capacitaciones()
        {
            this.Pry_CapacitacionBeneficiario = new HashSet<Pry_CapacitacionBeneficiario>();
        }
    
        public int IdCapacitacion { get; set; }
        public int IdFacilitador { get; set; }
        public string NombreCapacitacion { get; set; }
        public string DescripcionCapacitacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public byte Status { get; set; }
        public int IdTenant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_CapacitacionBeneficiario> Pry_CapacitacionBeneficiario { get; set; }
        public virtual Pry_Facilitadores Pry_Facilitadores { get; set; }
    }
}
