//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_ProductividadBeneficiario
    {
        public int IdProductividadBeneficiario { get; set; }
        public int IdBeneficiario { get; set; }
        public decimal AreaSembrada { get; set; }
        public string CultivoSembrado { get; set; }
        public decimal CantidadSembrada { get; set; }
        public decimal ProduccionCultivo { get; set; }
        public bool Eliminado { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_Beneficiarios Pry_Beneficiarios { get; set; }
    }
}
