//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Beneficiarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pry_Beneficiarios()
        {
            this.Pry_CapacitacionBeneficiario = new HashSet<Pry_CapacitacionBeneficiario>();
            this.Pry_ProductividadBeneficiario = new HashSet<Pry_ProductividadBeneficiario>();
        }
    
        public int IdBeneficiario { get; set; }
        public int IdObjetivo { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<decimal> extensionTerritorial { get; set; }
        public byte Status { get; set; }
        public int IdTenant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_CapacitacionBeneficiario> Pry_CapacitacionBeneficiario { get; set; }
        public virtual Pry_Objetivos Pry_Objetivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_ProductividadBeneficiario> Pry_ProductividadBeneficiario { get; set; }
    }
}
