//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Informes_Supuestos
    {
        public int IdInforme { get; set; }
        public int IdSupuesto { get; set; }
        public bool Valor { get; set; }
        public string Tipo { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_Informes Pry_Informes { get; set; }
        public virtual Pry_Supuestos Pry_Supuestos { get; set; }
    }
}
