//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_DatosVariables
    {
        public int IdDatosMuestra { get; set; }
        public int IdVariable { get; set; }
        public Nullable<double> Valor { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_DatosMuestras Pry_DatosMuestras { get; set; }
        public virtual Pry_Variables Pry_Variables { get; set; }
    }
}
