//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_DatosMuestras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pry_DatosMuestras()
        {
            this.Pry_DatosVariables = new HashSet<Pry_DatosVariables>();
            this.Pry_DatosVerificadores = new HashSet<Pry_DatosVerificadores>();
            this.Pry_Informes_Indicador = new HashSet<Pry_Informes_Indicador>();
        }
    
        public int IdDatosMuestra { get; set; }
        public Nullable<int> IdIndicador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Logro { get; set; }
        public string Observaciones { get; set; }
        public Nullable<double> Efectividad { get; set; }
        public Nullable<int> IdNivelAceptacionEfectividad { get; set; }
        public Nullable<double> Eficacia { get; set; }
        public Nullable<int> IdNivelAceptacionEficacia { get; set; }
        public Nullable<long> IdPeriodo { get; set; }
        public string USUARIOCREACION { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_Indicadores Pry_Indicadores { get; set; }
        public virtual Pry_NivelAceptacion Pry_NivelAceptacion { get; set; }
        public virtual PRY_PERIODOSPROYECTOS PRY_PERIODOSPROYECTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_DatosVariables> Pry_DatosVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_DatosVerificadores> Pry_DatosVerificadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pry_Informes_Indicador> Pry_Informes_Indicador { get; set; }
    }
}
