//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRY_EVALUACIONPROYECTOPERIODO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRY_EVALUACIONPROYECTOPERIODO()
        {
            this.PRY_EVALUACIONESACTIVIDADESPERIODO = new HashSet<PRY_EVALUACIONESACTIVIDADESPERIODO>();
        }
    
        public long IDPERIODO { get; set; }
        public int IDPROYECTO { get; set; }
        public string DATOSFINANCIEROS { get; set; }
        public string OBSERVACIONES { get; set; }
        public string RECOMENDACIONES { get; set; }
        public int IdTenant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRY_EVALUACIONESACTIVIDADESPERIODO> PRY_EVALUACIONESACTIVIDADESPERIODO { get; set; }
        public virtual PRY_PERIODOSPROYECTOS PRY_PERIODOSPROYECTOS { get; set; }
        public virtual Pry_Proyectos Pry_Proyectos { get; set; }
    }
}
