//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_CalendarioDonaciones
    {
        public int IdDonacion { get; set; }
        public int IdProyecto { get; set; }
        public int IdDonante { get; set; }
        public double Monto { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Org_Donantes Org_Donantes { get; set; }
        public virtual Pry_Proyectos Pry_Proyectos { get; set; }
    }
}
