//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pry_Informes_Encuestas
    {
        public int IdInforme { get; set; }
        public int IdPregunta { get; set; }
        public Nullable<bool> Respuesta { get; set; }
        public string Descripcion { get; set; }
        public int IdTenant { get; set; }
    
        public virtual M_Preguntas M_Preguntas { get; set; }
        public virtual Pry_Informes Pry_Informes { get; set; }
    }
}
