//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRY_INFORMESICADOCUMENTOS
    {
        public System.Guid IDDOCUMENTO { get; set; }
        public int IDINFORME { get; set; }
        public string DESCRIPCION { get; set; }
        public string URL { get; set; }
        public string NOMBRE { get; set; }
        public int TIPO { get; set; }
        public int IdTenant { get; set; }
    
        public virtual PRY_INFORMESICA PRY_INFORMESICA { get; set; }
    }
}
