//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tar_Listas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tar_Listas()
        {
            this.Tar_Tareas = new HashSet<Tar_Tareas>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public string Descripcion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Pry_Proyectos Pry_Proyectos { get; set; }
        public virtual Sys_Usuarios Sys_Usuarios { get; set; }
        public virtual Sys_Usuarios Sys_Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tar_Tareas> Tar_Tareas { get; set; }
    }
}
