//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdlumenMVC.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tar_Permisos_Bitacora
    {
        public int IdPermisoBitacora { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdVisita { get; set; }
        public string Permiso { get; set; }
        public int IdTenant { get; set; }
    
        public virtual Sys_Usuarios Sys_Usuarios { get; set; }
        public virtual Tar_Visitas Tar_Visitas { get; set; }
    }
}
